extends RichTextLabel

var input_text = ["[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", 
"[shake][color=#ffff00]ABCDEFG\nHIJKLMN\nOPQRSTU\nVWXYZ\n\nabcdefg\nhijklmn\nopqrstu\nvwxyz", ]
